# Basic Site Settings
title: CTF Walkthrough Portfolio
description: A collection of security assessment writeups and CTF solutions.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://idamilola52.github.io" # The base hostname & protocol for your site

# Theme Settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
